export type WorkCategory = "graphic" | "video" | "ai" | "selected";

export type Work = {
  id: string;
  category: WorkCategory;
  title: { en: string; ar: string };
  client: { en: string; ar: string };
  year: string;
  image: string;
  imageThumb: string;
  video?: string;
  accent: string;
  isAi?: boolean;
  brief: { en: string; ar: string };
  concept: { en: string; ar: string };
  role: { en: string; ar: string };
  tools: string[];
  process: { en: string; ar: string };
  result: { en: string; ar: string };
  hasBeforeAfter?: boolean;
};

export const works: Work[] = [
  // ===== GRAPHIC =====
  {
    id: "anjiko-product",
    category: "graphic",
    title: { en: "Anjiko — Product Ad", ar: "إعلان منتج — أنجيكو" },
    client: { en: "Anjiko", ar: "أنجيكو" },
    year: "2025",
    image: "/assets/work/anjiko.webp",
    imageThumb: "/assets/work/anjiko-thumb.webp",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #D4AF37 100%)",
    brief: { en: "Premium product advertising visual — clean, brand-safe, ready for paid media.", ar: "مرئي إعلاني فاخر للمنتج — نظيف، آمن للعلامة، جاهز للمدفوع." },
    concept: { en: "Editorial composition with gold-tinted lighting; product centered with crisp typography.", ar: "تركيب تحريري بإضاءة ذهبية الميل؛ المنتج في المنتصف وطباعة حادّة." },
    role: { en: "Graphic Designer & Art Director — concept, layout, typography, final delivery.", ar: "مصمم جرافيك ومدير فني — المفهوم، التخطيط، الطباعة، التسليم النهائي." },
    tools: ["Adobe Photoshop", "Adobe Illustrator", "Canva"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output for social and digital ads.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي للسوشال والإعلانات الرقمية." },
    result: { en: "Visuals shipped across IG, FB, and digital ads — clean, brand-safe, ready for paid media.", ar: "المرئيات نُشرت عبر IG وFB والإعلانات الرقمية — نظيفة، آمنة للعلامة، جاهزة للمدفوع." },
  },
  {
    id: "social-shawarma",
    category: "graphic",
    title: { en: "Shawarmaty — Social Ad", ar: "شاورماتي — إعلان سوشال" },
    client: { en: "Shawarmaty Food Brand", ar: "علامة شاورماتي الغذائية" },
    year: "2025",
    image: "/assets/work/social-shawarma.webp",
    imageThumb: "/assets/work/social-shawarma-thumb.webp",
    accent: "linear-gradient(135deg, #172A45 0%, #D4AF37 100%)",
    brief: { en: "Social media ad for Shawarmaty — shawarma wraps, fried chicken, and fries.", ar: "إعلان سوشال ميديا لشاورماتي — لفائف الشاورما والدجاج المقلي والبطاطس." },
    concept: { en: "Bold Arabic promotional text with appetizing food photography.", ar: "نص عربي ترويجي جريء مع تصوير طعام يثير الشهية." },
    role: { en: "Graphic Designer — concept, layout, typography, photo selection.", ar: "مصمم جرافيك — المفهوم، التخطيط، الطباعة، اختيار الصور." },
    tools: ["Adobe Photoshop", "Canva"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي." },
    result: { en: "Delivered for IG/FB feed and story ads.", ar: "سُلّم لمنشورات IG/FB وإعلانات القصص." },
  },
  {
    id: "social-mielle",
    category: "graphic",
    title: { en: "Mielle — Product Collage", ar: "مييلي — كولاج منتج" },
    client: { en: "Mielle Hair Care", ar: "منتجات مييلي للعناية بالشعر" },
    year: "2025",
    image: "/assets/work/social-mielle.webp",
    imageThumb: "/assets/work/social-mielle-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #64FFDA 100%)",
    brief: { en: "Social media collage showcasing Mielle hair care products with natural ingredients.", ar: "كولاج سوشال ميديا يعرض منتجات مييلي للعناية بالشعر بمكوّنات طبيعية." },
    concept: { en: "Clean product showcase featuring oats, honey, avocado, and tamanu ingredients.", ar: "عرض نظيف للمنتجات يبرز مكوّنات الشوفان والعسل والأفوكادو والتامانو." },
    role: { en: "Graphic Designer — collage, layout, typography, photo selection.", ar: "مصمم جرافيك — الكولاج، التخطيط، الطباعة، اختيار الصور." },
    tools: ["Adobe Photoshop", "Canva"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي." },
    result: { en: "Delivered for IG and FB product showcase.", ar: "سُلّم لعرض المنتجات على IG وFB." },
  },
  {
    id: "carousel-health-1",
    category: "graphic",
    title: { en: "Healthy Diet — Carousel", ar: "حمية صحية — كاروسيل" },
    client: { en: "Health & Fitness Brand", ar: "علامة صحة ولياقة" },
    year: "2025",
    image: "/assets/work/carousel-health-1.webp",
    imageThumb: "/assets/work/carousel-health-1-thumb.webp",
    accent: "linear-gradient(135deg, #172A45 0%, #64FFDA 100%)",
    brief: { en: "Carousel ad for a 7-day healthy diet and fitness program.", ar: "كاروسيل إعلاني لبرنامج حمية ولياقة لمدة 7 أيام." },
    concept: { en: "Strong visual featuring a fit person with a dumbbell and a bowl of nutritious food.", ar: "مرئي قوي يظهر شخص رياضي مع دمبل ووعاء طعام مغذّي." },
    role: { en: "Graphic Designer — concept, layout, typography, photo editing.", ar: "مصمم جرافيك — المفهوم، التخطيط، الطباعة، تحرير الصور." },
    tools: ["Adobe Photoshop", "Canva"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي." },
    result: { en: "Delivered as IG carousel for the campaign.", ar: "سُلّم ككاروسيل IG للحملة." },
  },
  {
    id: "carousel-design-1",
    category: "graphic",
    title: { en: "Creative Sheep — Brand Slide", ar: "إبداعي شيب — شريحة علامة" },
    client: { en: "Creative Sheep Studio", ar: "استوديو إبداعي شيب" },
    year: "2025",
    image: "/assets/work/carousel-design-1.webp",
    imageThumb: "/assets/work/carousel-design-1-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    brief: { en: "Brand slide for a creative studio — services showcase with golden eye symbol.", ar: "شريحة علامة لاستوديو إبداعي — عرض خدمات برمز عين ذهبي." },
    concept: { en: "Stylized golden eye with Arabic inspirational messaging about The Beginning.", ar: "عين ذهبية مصمّمة مع رسالة عربية ملهمة عن البداية." },
    role: { en: "Graphic Designer — concept, layout, typography.", ar: "مصمم جرافيك — المفهوم، التخطيط، الطباعة." },
    tools: ["Adobe Photoshop", "Adobe Illustrator"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي." },
    result: { en: "Delivered as part of studio services carousel.", ar: "سُلّم كجزء من كاروسيل خدمات الاستوديو." },
  },
  {
    id: "carousel-time",
    category: "graphic",
    title: { en: "Time Management — Infographic", ar: "إدارة الوقت — إنفوجرافيك" },
    client: { en: "Educational Content", ar: "محتوى تعليمي" },
    year: "2025",
    image: "/assets/work/carousel-time.webp",
    imageThumb: "/assets/work/carousel-time-thumb.webp",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #F5D77E 100%)",
    brief: { en: "Infographic about time management with mountain climber metaphor.", ar: "إنفوجرافيك عن إدارة الوقت بمجاز متسلّق الجبل." },
    concept: { en: "Climber ascending a mountain with stopwatch and upward arrow.", ar: "متسلّق يصعد جبلاً مع ساعة إيقاف وسهم صاعد." },
    role: { en: "Graphic Designer — concept, layout, typography, illustration.", ar: "مصمم جرافيك — المفهوم، التخطيط، الطباعة، الرسم." },
    tools: ["Adobe Photoshop", "Adobe Illustrator"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي." },
    result: { en: "Delivered as educational carousel content.", ar: "سُلّم كمحتوى كاروسيل تعليمي." },
  },

  // ===== AI =====
  {
    id: "ai-pizza",
    category: "ai",
    title: { en: "AI Ad — Pizza", ar: "إعلان ذكاء اصطناعي — بيتزا" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/ai-pizza.webp",
    imageThumb: "/assets/work/ai-pizza-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    isAi: true,
    brief: { en: "AI-generated ad visual for a pizza brand — preserve the product's identity while elevating the scene.", ar: "مرئي إعلاني مولّد بالذكاء الاصطناعي لعلامة بيتزا — حفاظ على هوية المنتج مع رفع قيمة المشهد." },
    concept: { en: "Cinematic lighting, appetite-driven composition, brand-safe typography.", ar: "إضاءة سينمائية، تركيب يثير الشهية، طباعة آمنة للعلامة." },
    role: { en: "Creative Director & AI Practitioner — idea, AI generation, direction, editing, final visual.", ar: "مدير إبداعي وممارس ذكاء اصطناعي — الفكرة، التوليد، التوجيه، التحرير، المرئي النهائي." },
    tools: ["Gemini", "Nano Banana", "Adobe Photoshop"],
    process: { en: "Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "الفكرة ← التوليد بالذكاء الاصطناعي ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "Premium AI ad visual delivered for digital advertising.", ar: "مرئي إعلاني فاخر بالذكاء الاصطناعي سُلّم للإعلانات الرقمية." },
  },

  // ===== VIDEO =====
  {
    id: "video-corn-cheese",
    category: "video",
    title: { en: "Corn & Cheese — Ad Spot", ar: "إعلان — ذرة بالجبن" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/video-corn-cheese.webp",
    imageThumb: "/assets/work/video-corn-cheese-thumb.webp",
    video: "/assets/videos/video-corn-cheese.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #D4AF37 100%)",
    brief: { en: "Product video for a corn-and-cheese dish — warm, appetizing, social-ready.", ar: "فيديو منتج لطبق ذرة بالجبن — دافئ، يثير الشهية، جاهز للسوشال." },
    concept: { en: "Warm tones, steam and cheese pull close-ups, fast cuts.", ar: "درجات دافئة، لقطات قريبة للبخار وسحب الجبن، قصّات سريعة." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["CapCut", "Adobe Premiere Pro"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG/FB video ads.", ar: "سُلّم لإعلانات فيديو على IG/FB." },
  },
  {
    id: "video-flash-fix",
    category: "video",
    title: { en: "Flash Fix — Product Spot", ar: "إعلان — فلاش فيكس" },
    client: { en: "Consumer Product", ar: "منتج استهلاكي" },
    year: "2025",
    image: "/assets/work/video-flash-fix.webp",
    imageThumb: "/assets/work/video-flash-fix-thumb.webp",
    video: "/assets/videos/video-flash-fix.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #64FFDA 100%)",
    brief: { en: "Product ad video — clean modern edits, color enhancement.", ar: "فيديو إعلان منتج — قصّات حديثة نظيفة، تعزيز ألوان." },
    concept: { en: "Modern product framing, transitions, sound layer.", ar: "تأطير حديث للمنتج، انتقالات، طبقة صوتية." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["Adobe Premiere Pro", "CapCut", "Adobe After Effects"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG, FB, and TikTok ads.", ar: "سُلّم لإعلانات IG وFB وTikTok." },
  },
  {
    id: "video-lenovo",
    category: "video",
    title: { en: "Lenovo Laptop — Promo", ar: "ترويج — لابتوب لينوفو" },
    client: { en: "Tech Retail", ar: "تجزئة تقنية" },
    year: "2025",
    image: "/assets/work/video-lenovo-laptop.webp",
    imageThumb: "/assets/work/video-lenovo-laptop-thumb.webp",
    video: "/assets/videos/video-lenovo-laptop.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #D4AF37 100%)",
    brief: { en: "Promotional video for a Lenovo laptop — feature-driven, premium tech feel.", ar: "فيديو ترويجي للابتوب لينوفو — يحمل الميزات، بإحساس تقني فاخر." },
    concept: { en: "Clean tech aesthetic, smooth transitions, feature callouts.", ar: "جمالية تقنية نظيفة، انتقالات سلسة، إبراز الميزات." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "CapCut"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Promo delivered for digital and YouTube ads.", ar: "إعلان ترويجي سُلّم للإعلانات الرقمية ويوتيوب." },
  },
  {
    id: "video-fashion",
    category: "video",
    title: { en: "Fashion — Promo Spot", ar: "إعلان تسويقي — ألبسة" },
    client: { en: "Fashion Brand", ar: "علامة أزياء" },
    year: "2025",
    image: "/assets/work/video-fashion.webp",
    imageThumb: "/assets/work/video-fashion-thumb.webp",
    video: "/assets/videos/video-fashion.mp4",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #F5D77E 100%)",
    brief: { en: "Marketing video for a fashion brand — editorial, modern, social-ready.", ar: "فيديو تسويقي لعلامة أزياء — تحريري، عصري، جاهز للسوشال." },
    concept: { en: "Editorial pacing, model close-ups, sound sync, premium feel.", ar: "إيقاع تحريري، لقطات قريبة للعارض، تزامن صوتي، إحساس فاخر." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "CapCut", "InShot"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG Reels, FB, and TikTok ads.", ar: "سُلّم لإعلانات IG Reels وFB وTikTok." },
  },
  {
    id: "video-villa",
    category: "video",
    title: { en: "Villa — Real Estate Spot", ar: "إعلان — فيلا" },
    client: { en: "Real Estate", ar: "عقارات" },
    year: "2025",
    image: "/assets/work/video-villa.webp",
    imageThumb: "/assets/work/video-villa-thumb.webp",
    video: "/assets/videos/video-villa.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    brief: { en: "Real estate promo video — cinematic walk-throughs, premium feel.", ar: "فيديو ترويجي عقاري — جولات سينمائية، إحساس فاخر." },
    concept: { en: "Slow cinematic pans, warm light, music-driven pacing.", ar: "تحريكات سينمائية بطيئة، إضاءة دافئة، إيقاع موسيقي." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "CapCut"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for social and direct client presentations.", ar: "سُلّم للسوشال والعروض المباشرة للعملاء." },
  },
  {
    id: "video-hospital",
    category: "video",
    title: { en: "Hospital — Promo Spot", ar: "إعلان — مشفى السيدة" },
    client: { en: "Healthcare", ar: "رعاية صحية" },
    year: "2025",
    image: "/assets/work/video-hospital.webp",
    imageThumb: "/assets/work/video-hospital-thumb.webp",
    video: "/assets/videos/video-hospital.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #64FFDA 100%)",
    brief: { en: "Promotional video for a hospital — clean, trustworthy, calm.", ar: "فيديو ترويجي لمشفى — نظيف، موثوق، هادئ." },
    concept: { en: "Calm pacing, clean light, soft sound design.", ar: "إيقاع هادئ، إضاءة نظيفة، تصميم صوتي ناعم." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for social and direct client presentations.", ar: "سُلّم للسوشال والعروض المباشرة للعملاء." },
  },
  {
    id: "video-cocktail",
    category: "video",
    title: { en: "Cocktail — Dessert Spot", ar: "إعلان — كوكتيل حلويات" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/video-cocktail.webp",
    imageThumb: "/assets/work/video-cocktail-thumb.webp",
    video: "/assets/videos/video-cocktail.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #F5D77E 100%)",
    brief: { en: "Vertical dessert video — cream, KitKat, and cocktail layers, ASMR-style.", ar: "فيديو عمودي للحلويات — قشطة وكيت كات وطبقات الكوكتيل بأسلوب ASMR." },
    concept: { en: "Vertical 9:16, layered reveal, slow motion, appetizing close-ups.", ar: "عمودي 9:16، كشف طبقات، حركة بطيئة، لقطات قريبة تثير الشهية." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["CapCut", "Adobe Premiere Pro"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered as IG Reel and TikTok vertical ad.", ar: "سُلّم كـ Reel على IG وإعلان عمودي على TikTok." },
  },
  {
    id: "video-song-sahsah",
    category: "video",
    title: { en: "Sahsah — Song Video", ar: "صحصح — فيديو أغنية" },
    client: { en: "Personal Project", ar: "مشروع شخصي" },
    year: "2025",
    image: "/assets/work/video-song-sahsah.webp",
    imageThumb: "/assets/work/video-song-sahsah-thumb.webp",
    video: "/assets/videos/video-song-sahsah.mp4",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #D4AF37 100%)",
    brief: { en: "Song video edit — clip with music sync and visual rhythm.", ar: "تحرير فيديو أغنية — مقطع مع تزامن موسيقي وإيقاع بصري." },
    concept: { en: "Music-driven pacing, lyric-friendly cuts, atmospheric visuals.", ar: "إيقاع يحكمه الموسيقى، قصّات تناسب الكلمات، مرئيات أجواء." },
    role: { en: "Video Editor — edit, transitions, color, sound sync.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، تزامن الصوت." },
    tools: ["Adobe Premiere Pro", "CapCut"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for social song video sharing.", ar: "سُلّم لمشاركة فيديو الأغنية على السوشال." },
  },

  // ===== SELECTED PROJECT =====
  {
    id: "selected-brand-campaign",
    category: "selected",
    title: { en: "Selected Project — Brand Campaign", ar: "مشروع مختار — حملة علامة" },
    client: { en: "Premium Brand", ar: "علامة فاخرة" },
    year: "2025",
    image: "/assets/work/ai-pizza.webp",
    imageThumb: "/assets/work/ai-pizza-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    isAi: true,
    brief: { en: "End-to-end campaign combining graphic design, video editing, and AI-generated content — built to feel like one unified story.", ar: "حملة شاملة تجمع تصميم الجرافيك وتحرير الفيديو والمحتوى المولّد بالذكاء الاصطناعي — مبنية لتشعر كقصة واحدة موحّدة." },
    concept: { en: "Editorial dark direction with gold accents, cinematic AI-generated scenes, and a real product preserved across every deliverable.", ar: "توجيه تحريري داكن بلمسات ذهبية، مشاهد سينمائية مولّدة بالذكاء الاصطناعي، ومنتج حقيقي محفوظ عبر كل مخرَج." },
    role: { en: "Creative Director · Graphic Designer · Video Editor · AI Content Creator — full pipeline from idea to final cut.", ar: "مدير إبداعي · مصمم جرافيك · مونتير فيديو · صانع محتوى بالذكاء الاصطناعي — الخط الكامل من الفكرة إلى القصّة النهائية." },
    tools: ["Adobe Photoshop", "Adobe Premiere Pro", "Adobe After Effects", "Gemini", "Nano Banana", "Runway", "Kling", "ElevenLabs", "Claude"],
    process: { en: "Project → Brief → Concept → My Role → Tools → Process → Final Result. AI projects flow: Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "المشروع ← الموجز ← المفهوم ← دوري ← الأدوات ← العملية ← النتيجة. مشاريع الذكاء الاصطناعي: الفكرة ← التوليد ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "An integrated campaign delivered across IG, FB, and digital ads — design, video, and AI in one brand voice.", ar: "حملة متكاملة سُلّمت عبر IG وFB والإعلانات الرقمية — تصميم وفيديو وذكاء اصطناعي بصوت علامة واحد." },
  },
];
