export type WorkCategory = "graphic" | "video" | "ai" | "selected";

export type Work = {
  id: string;
  category: WorkCategory;
  title: { en: string; ar: string };
  client: { en: string; ar: string };
  year: string;
  image: string;
  imageThumb: string;
  video?: string;
  accent: string;
  isAi?: boolean;
  brief: { en: string; ar: string };
  concept: { en: string; ar: string };
  role: { en: string; ar: string };
  tools: string[];
  process: { en: string; ar: string };
  result: { en: string; ar: string };
  hasBeforeAfter?: boolean;
};

export const works: Work[] = [
  // GRAPHIC
  {
    id: "anjiko-product",
    category: "graphic",
    title: { en: "Anjiko — Product Ad", ar: "إعلان منتج — أنجيكو" },
    client: { en: "Anjiko", ar: "أنجيكو" },
    year: "2025",
    image: "/assets/work/anjiko.webp",
    imageThumb: "/assets/work/anjiko-thumb.webp",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #D4AF37 100%)",
    brief: { en: "Premium product advertising visual — clean, brand-safe, ready for paid media.", ar: "مرئي إعلاني فاخر للمنتج — نظيف، آمن للعلامة، جاهز للمدفوع." },
    concept: { en: "Editorial composition with gold-tinted lighting; product centered with crisp typography.", ar: "تركيب تحريري بإضاءة ذهبية الميل؛ المنتج في المنتصف وطباعة حادّة." },
    role: { en: "Graphic Designer & Art Director — concept, layout, typography, final delivery.", ar: "مصمم جرافيك ومدير فني — المفهوم، التخطيط، الطباعة، التسليم النهائي." },
    tools: ["Adobe Photoshop", "Adobe Illustrator", "Canva"],
    process: { en: "Brief → Concept → Visual Direction → Design → Final Output for social and digital ads.", ar: "الموجز ← المفهوم ← التوجيه البصري ← التصميم ← الإخراج النهائي للسوشال والإعلانات الرقمية." },
    result: { en: "Visuals shipped across IG, FB, and digital ads — clean, brand-safe, ready for paid media.", ar: "المرئيات نُشرت عبر IG وFB والإعلانات الرقمية — نظيفة، آمنة للعلامة، جاهزة للمدفوع." },
  },

  // AI
  {
    id: "ai-pizza",
    category: "ai",
    title: { en: "AI Ad — Pizza", ar: "إعلان ذكاء اصطناعي — بيتزا" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/ai-pizza.webp",
    imageThumb: "/assets/work/ai-pizza-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    isAi: true,
    brief: { en: "AI-generated ad visual for a pizza brand — preserve the product's identity while elevating the scene.", ar: "مرئي إعلاني مولّد بالذكاء الاصطناعي لعلامة بيتزا — حفاظ على هوية المنتج مع رفع قيمة المشهد." },
    concept: { en: "Cinematic lighting, appetite-driven composition, brand-safe typography.", ar: "إضاءة سينمائية، تركيب يثير الشهية، طباعة آمنة للعلامة." },
    role: { en: "Creative Director & AI Practitioner — idea, AI generation, direction, editing, final visual.", ar: "مدير إبداعي وممارس ذكاء اصطناعي — الفكرة، التوليد، التوجيه، التحرير، المرئي النهائي." },
    tools: ["Gemini", "Nano Banana", "Adobe Photoshop"],
    process: { en: "Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "الفكرة ← التوليد بالذكاء الاصطناعي ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "Premium AI ad visual delivered for digital advertising.", ar: "مرئي إعلاني فاخر بالذكاء الاصطناعي سُلّم للإعلانات الرقمية." },
    hasBeforeAfter: true,
  },
  {
    id: "ai-icecream",
    category: "ai",
    title: { en: "AI Ad — Ice Cream", ar: "إعلان ذكاء اصطناعي — بوظة" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/ai-icecream.webp",
    imageThumb: "/assets/work/ai-icecream-thumb.webp",
    accent: "linear-gradient(135deg, #172A45 0%, #64FFDA 100%)",
    isAi: true,
    brief: { en: "AI advertising visual for an ice cream brand — fresh, premium, social-ready.", ar: "مرئي إعلاني بالذكاء الاصطناعي لعلامة بوظة — منعش، فاخر، جاهز للسوشال." },
    concept: { en: "Cool palette, soft highlights, gold-accented typography for premium feel.", ar: "لوحة ألوان باردة، إضاءات ناعمة، طباعة ذهبية الميل لإحساس فاخر." },
    role: { en: "Creative Director & AI Practitioner — idea, generation, direction, editing.", ar: "مدير إبداعي وممارس ذكاء اصطناعي — الفكرة، التوليد، التوجيه، التحرير." },
    tools: ["Gemini", "Nano Banana", "Adobe Photoshop"],
    process: { en: "Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "الفكرة ← التوليد بالذكاء الاصطناعي ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "Premium AI ad visual delivered for IG, FB, and digital ads.", ar: "مرئي إعلاني فاخر بالذكاء الاصطناعي سُلّم لـ IG وFB والإعلانات الرقمية." },
    hasBeforeAfter: true,
  },
  {
    id: "ai-loan",
    category: "ai",
    title: { en: "AI Ad — Loan Service", ar: "إعلان ذكاء اصطناعي — خدمة قروض" },
    client: { en: "Financial Service", ar: "خدمة مالية" },
    year: "2025",
    image: "/assets/work/ai-loan.webp",
    imageThumb: "/assets/work/ai-loan-thumb.webp",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #AA7C11 100%)",
    isAi: true,
    brief: { en: "AI-generated ad visual for a financial/loan service — trustworthy and modern.", ar: "مرئي إعلاني مولّد بالذكاء الاصطناعي لخدمة مالية/قروض — موثوق وعصري." },
    concept: { en: "Clean composition, premium trust signals, modern typography.", ar: "تركيب نظيف، إشارات ثقة فاخرة، طباعة عصرية." },
    role: { en: "Creative Director & AI Practitioner — idea, generation, direction, editing, delivery.", ar: "مدير إبداعي وممارس ذكاء اصطناعي — الفكرة، التوليد، التوجيه، التحرير، التسليم." },
    tools: ["Gemini", "Google Flow", "Adobe Photoshop"],
    process: { en: "Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "الفكرة ← التوليد بالذكاء الاصطناعي ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "Trust-driven AI ad visual delivered for digital advertising.", ar: "مرئي إعلاني بالذكاء الاصطناعي يحمل إشارات ثقة سُلّم للإعلانات الرقمية." },
    hasBeforeAfter: true,
  },

  // VIDEO (with real video URLs)
  {
    id: "video-turkish-potato",
    category: "video",
    title: { en: "Turkish Potato — Ad Spot", ar: "إعلان — بطاطا تركية" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/video-turkish-potato.webp",
    imageThumb: "/assets/work/video-turkish-potato-thumb.webp",
    video: "/assets/videos/video-turkish-potato.mp4",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #64FFDA 100%)",
    brief: { en: "15-second product video ad — appetite-driven cuts with sound design.", ar: "إعلان منتج مدته 15 ثانية — قصّات تثير الشهرة مع تصميم صوتي." },
    concept: { en: "Macro close-ups, smooth motion, color enhancement, brand-safe framing.", ar: "لقطات ماكرو قريبة، حركة سلسة، تعزيز ألوان، تأطير آمن للعلامة." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "CapCut", "Adobe After Effects"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Short ad delivered for IG Reels and FB Ads.", ar: "إعلان قصير سُلّم لـ IG Reels وFB Ads." },
  },
  {
    id: "video-corn-cheese",
    category: "video",
    title: { en: "Corn & Cheese — Ad Spot", ar: "إعلان — ذرة بالجبن" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/video-corn-cheese.webp",
    imageThumb: "/assets/work/video-corn-cheese-thumb.webp",
    video: "/assets/videos/video-corn-cheese.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #D4AF37 100%)",
    brief: { en: "Product video for a corn-and-cheese dish — warm, appetizing, social-ready.", ar: "فيديو منتج لطبق ذرة بالجبن — دافئ، يثير الشهية، جاهز للسوشال." },
    concept: { en: "Warm tones, steam and cheese pull close-ups, fast cuts.", ar: "درجات دافئة، لقطات قريبة للبخار وسحب الجبن، قصّات سريعة." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["CapCut", "Adobe Premiere Pro"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG/FB video ads.", ar: "سُلّم لإعلانات فيديو على IG/FB." },
  },
  {
    id: "video-cake",
    category: "video",
    title: { en: "Cake — Ad Spot", ar: "إعلان — كيك" },
    client: { en: "Food & Beverage", ar: "مطاعم ومشروبات" },
    year: "2025",
    image: "/assets/work/video-cake.webp",
    imageThumb: "/assets/work/video-cake-thumb.webp",
    video: "/assets/videos/video-cake.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #F5D77E 100%)",
    brief: { en: "Appetite-driven cake ad — slow reveal, soft light, sound design.", ar: "إعلان كيك يثير الشهية — كشف بطيء، إضاءة ناعمة، تصميم صوتي." },
    concept: { en: "Slow-motion close-ups, warm light, ASMR sound layer.", ar: "لقطات بطيئة قريبة، إضاءة دافئة، طبقة صوت ASMR." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["CapCut", "Adobe Premiere Pro", "InShot"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Short ad delivered for IG Reels and TikTok.", ar: "إعلان قصير سُلّم لـ IG Reels وTikTok." },
  },
  {
    id: "video-cornflakes",
    category: "video",
    title: { en: "Cornflakes — Ad Spot", ar: "إعلان — كورن فليكس كورنيتو" },
    client: { en: "Consumer Product", ar: "منتج استهلاكي" },
    year: "2025",
    image: "/assets/work/video-cornflakes.webp",
    imageThumb: "/assets/work/video-cornflakes-thumb.webp",
    video: "/assets/videos/video-cornflakes.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #64FFDA 100%)",
    brief: { en: "Product video for cornflakes — energetic, bright, family-friendly.", ar: "فيديو منتج للكورن فليكس — حيوي، مشرق، مناسب للعائلة." },
    concept: { en: "Bright lighting, fast-paced cuts, sound sync to music.", ar: "إضاءة مشرقة، قصّات سريعة، تزامن صوتي مع الموسيقى." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["CapCut", "Adobe Premiere Pro"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG/FB video ads.", ar: "سُلّم لإعلانات فيديو على IG/FB." },
  },
  {
    id: "video-flash-fix",
    category: "video",
    title: { en: "Flash Fix — Product Spot", ar: "إعلان — فلاش فيكس" },
    client: { en: "Consumer Product", ar: "منتج استهلاكي" },
    year: "2025",
    image: "/assets/work/video-flash-fix.webp",
    imageThumb: "/assets/work/video-flash-fix-thumb.webp",
    video: "/assets/videos/video-flash-fix.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #64FFDA 100%)",
    brief: { en: "Product ad video — clean modern edits, color enhancement.", ar: "فيديو إعلان منتج — قصّات حديثة نظيفة، تعزيز ألوان." },
    concept: { en: "Modern product framing, transitions, sound layer.", ar: "تأطير حديث للمنتج، انتقالات، طبقة صوتية." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["Adobe Premiere Pro", "CapCut", "Adobe After Effects"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG, FB, and TikTok ads.", ar: "سُلّم لإعلانات IG وFB وTikTok." },
  },
  {
    id: "video-lenovo",
    category: "video",
    title: { en: "Lenovo Laptop — Promo", ar: "ترويج — لابتوب لينوفو" },
    client: { en: "Tech Retail", ar: "تجزئة تقنية" },
    year: "2025",
    image: "/assets/work/video-lenovo-laptop.webp",
    imageThumb: "/assets/work/video-lenovo-laptop-thumb.webp",
    video: "/assets/videos/video-lenovo-laptop.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #D4AF37 100%)",
    brief: { en: "Promotional video for a Lenovo laptop — feature-driven, premium tech feel.", ar: "فيديو ترويجي للابتوب لينوفو — يحمل الميزات، بإحساس تقني فاخر." },
    concept: { en: "Clean tech aesthetic, smooth transitions, feature callouts.", ar: "جمالية تقنية نظيفة، انتقالات سلسة، إبراز الميزات." },
    role: { en: "Video Editor — edit, transitions, color, sound.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "CapCut"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Promo delivered for digital and YouTube ads.", ar: "إعلان ترويجي سُلّم للإعلانات الرقمية ويوتيوب." },
  },
  {
    id: "video-fashion",
    category: "video",
    title: { en: "Fashion — Promo Spot", ar: "إعلان تسويقي — ألبسة" },
    client: { en: "Fashion Brand", ar: "علامة أزياء" },
    year: "2025",
    image: "/assets/work/video-fashion.webp",
    imageThumb: "/assets/work/video-fashion-thumb.webp",
    video: "/assets/videos/video-fashion.mp4",
    accent: "linear-gradient(135deg, #1E3A5F 0%, #F5D77E 100%)",
    brief: { en: "Marketing video for a fashion brand — editorial, modern, social-ready.", ar: "فيديو تسويقي لعلامة أزياء — تحريري، عصري، جاهز للسوشال." },
    concept: { en: "Editorial pacing, model close-ups, sound sync, premium feel.", ar: "إيقاع تحريري، لقطات قريبة للعارض، تزامن صوتي، إحساس فاخر." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "CapCut", "InShot"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for IG Reels, FB, and TikTok ads.", ar: "سُلّم لإعلانات IG Reels وFB وTikTok." },
  },
  {
    id: "video-villa",
    category: "video",
    title: { en: "Villa — Real Estate Spot", ar: "إعلان — فيلا" },
    client: { en: "Real Estate", ar: "عقارات" },
    year: "2025",
    image: "/assets/work/video-villa.webp",
    imageThumb: "/assets/work/video-villa-thumb.webp",
    video: "/assets/videos/video-villa.mp4",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    brief: { en: "Real estate promo video — cinematic walk-throughs, premium feel.", ar: "فيديو ترويجي عقاري — جولات سينمائية، إحساس فاخر." },
    concept: { en: "Slow cinematic pans, warm light, music-driven pacing.", ar: "تحريكات سينمائية بطيئة، إضاءة دافئة، إيقاع موسيقي." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "CapCut"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for social and direct client presentations.", ar: "سُلّم للسوشال والعروض المباشرة للعملاء." },
  },
  {
    id: "video-hospital",
    category: "video",
    title: { en: "Hospital — Promo Spot", ar: "إعلان — مشفى السيدة" },
    client: { en: "Healthcare", ar: "رعاية صحية" },
    year: "2025",
    image: "/assets/work/video-hospital.webp",
    imageThumb: "/assets/work/video-hospital-thumb.webp",
    video: "/assets/videos/video-hospital.mp4",
    accent: "linear-gradient(135deg, #172A45 0%, #64FFDA 100%)",
    brief: { en: "Promotional video for a hospital — clean, trustworthy, calm.", ar: "فيديو ترويجي لمشفى — نظيف، موثوق، هادئ." },
    concept: { en: "Calm pacing, clean light, soft sound design.", ar: "إيقاع هادئ، إضاءة نظيفة، تصميم صوتي ناعم." },
    role: { en: "Video Editor — edit, transitions, color, sound, final delivery.", ar: "مونتير فيديو — التحرير، الانتقالات، اللون، الصوت، التسليم النهائي." },
    tools: ["Adobe Premiere Pro", "Adobe After Effects"],
    process: { en: "Brief → Concept → Visual Direction → Production → Editing → Final Output.", ar: "الموجز ← المفهوم ← التوجيه البصري ← الإنتاج ← التحرير ← الإخراج النهائي." },
    result: { en: "Delivered for social and direct client presentations.", ar: "سُلّم للسوشال والعروض المباشرة للعملاء." },
  },

  // SELECTED PROJECT
  {
    id: "selected-brand-campaign",
    category: "selected",
    title: { en: "Selected Project — Brand Campaign", ar: "مشروع مختار — حملة علامة" },
    client: { en: "Premium Brand", ar: "علامة فاخرة" },
    year: "2025",
    image: "/assets/work/ai-pizza.webp",
    imageThumb: "/assets/work/ai-pizza-thumb.webp",
    accent: "linear-gradient(135deg, #0A192F 0%, #D4AF37 100%)",
    isAi: true,
    brief: { en: "End-to-end campaign combining graphic design, video editing, and AI-generated content — built to feel like one unified story.", ar: "حملة شاملة تجمع تصميم الجرافيك وتحرير الفيديو والمحتوى المولّد بالذكاء الاصطناعي — مبنية لتشعر كقصة واحدة موحّدة." },
    concept: { en: "Editorial dark direction with gold accents, cinematic AI-generated scenes, and a real product preserved across every deliverable.", ar: "توجيه تحريري داكن بلمسات ذهبية، مشاهد سينمائية مولّدة بالذكاء الاصطناعي، ومنتج حقيقي محفوظ عبر كل مخرَج." },
    role: { en: "Creative Director · Graphic Designer · Video Editor · AI Content Creator — full pipeline from idea to final cut.", ar: "مدير إبداعي · مصمم جرافيك · مونتير فيديو · صانع محتوى بالذكاء الاصطناعي — الخط الكامل من الفكرة إلى القصّة النهائية." },
    tools: ["Adobe Photoshop", "Adobe Premiere Pro", "Adobe After Effects", "Gemini", "Nano Banana", "Runway", "Kling", "ElevenLabs", "Claude"],
    process: { en: "Project → Brief → Concept → My Role → Tools → Process → Final Result. AI projects flow: Idea → AI Generation → Creative Direction → Editing → Final Visual.", ar: "المشروع ← الموجز ← المفهوم ← دوري ← الأدوات ← العملية ← النتيجة. مشاريع الذكاء الاصطناعي: الفكرة ← التوليد ← التوجيه الإبداعي ← التحرير ← المرئي النهائي." },
    result: { en: "An integrated campaign delivered across IG, FB, and digital ads — design, video, and AI in one brand voice.", ar: "حملة متكاملة سُلّمت عبر IG وFB والإعلانات الرقمية — تصميم وفيديو وذكاء اصطناعي بصوت علامة واحد." },
    hasBeforeAfter: true,
  },
];
